### ISSUE TITLE
Support URL query

### ISSUE THREAD

**Issue by MoMannn** [0xcert/erc721-validator-ui#1]
We would like a specific URL, including a query string, to correspond to a specific scan.

This project is really great and we should expect that people are going to want to directly link to test results.

# Work plan

- [x] When starting a scan use Javascript History API to change URL to https://erc721validator.org?address=XXXX&network=mainnet
- [x] Update link from CryptoKitties: 0x06... to go to https://erc721validator.org?address=XXXX

**Comment by fulldecent** [comment]
This will go on stage at 1pm Hong Kong time.

Please implement by that time if possible.

**Comment by davision** [comment]
Sorry, I didn't make it. For now, you can pre-populate address field with https://erc721validator.org?address=XXXX. Do we want the test already run with URL query?
